### ISSUE TITLE
Radio button is broken on iOS 10 and 12

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-radio-button#109]
The previous version (before adding `change` event works).

@Haprog will add more details.

**Comment by Haprog** [comment]
iOS 9.3:
- v1.1.5 and v1.2.1: Works perfectly

iOS 10.3.1:
- v1.1.5 and v1.2.1: Requires 2 clicks to select a radio button and when clicking around sometimes you can select more than 1 from a radio group. Seems like the selection doesn't fully update the visual state until you focus out of the radio button or group. But also you can be left in a state where all seem to be checked but you are focused out already.

iOS 11.3:
- v1.1.5 and v1.2.1: Works perfectly

iOS 12.2:
- v1.1.5: Works perfectly
- v1.2.1: Most of the time selecting a radio button just doesn't work. Sometimes randomly it works.
