### ISSUE TITLE
Radio Button Error Labels disappear on blur

### ISSUE THREAD

**Issue by web-padawan** [vaadin/vaadin-radio-button#179]
_From @evmatt on February 1, 2019 9:52_

In a Vaadin application running on 12.0.0 a bug has been observed on a radio button group where validation results in an error and the error message is displayed, but then disappears on blur. This does appear to be linked to vaadin/vaadin-radio-button-flow#80, but does not appear to have been solved by the related fix. Looking at the changelogs it appears that this fix should be incorporated in Vaadin 12.0.0.

I have replicated this in a Vaadin starter running Vaadin version 12.0.5. The following code replicates the issue.

```
public class MainView extends VerticalLayout {

	public MainView() {
		RadioButtonGroup<String> group = new RadioButtonGroup<>();
		group.setItems("foo", "bar", "baz");
		group.setLabel("Group label");
		group.setErrorMessage("Invalid");
		addBinder(group);
		
		add(group);
	}

	private void addBinder(RadioButtonGroup<String> group) {
		Binder<TestBean> binder = new Binder<>();
		binder.forField(group).withValidator(value -> !value.equals("baz"), "Incorrect selection").bind(TestBean::getTest, TestBean::setTest);
	}
}
```

`TestBean` is a standard bean with a single String field `test` and a getter and setter.

This behaviour has been observed in Chrome and Firefox.

_Copied from original issue: vaadin/vaadin-radio-button#102_

**Comment by javier-godoy** [comment]
This issue is still present on Vaadin 14.4.2

```    	Binder<AtomicReference<String>> rbgBinder = new Binder<>();
    	RadioButtonGroup<String> rbg = new RadioButtonGroup<>();
    	rbg.setItems("valid 1", "valid 2", "invalid");
    	rbgBinder.forField(rbg)
    	         .withValidator(value->!"invalid".equals(value), "Value is invalid")
    	         .bind(AtomicReference::get, AtomicReference::set);    	
    	add(rbg, new TextField());
``` 
![rbgissue](https://user-images.githubusercontent.com/11554739/97888183-9cf2c880-1d09-11eb-9539-14412fb4d495.gif)
