### ISSUE TITLE
Radio Button Group deselect/un-select not works

### ISSUE THREAD

**Issue by bishwajitcse** [vaadin/vaadin-radio-button#181]
When trying to deselect radio button group with setValue(null). than not deselect the selected radio button.
radioButtonGroup.setValue(null)

**Comment by web-padawan** [comment]
Tried with the following example and could not reproduce:

```java
RadioButtonGroup<String> radioGroup = new RadioButtonGroup<>();
radioGroup.setLabel("Label");
radioGroup.setItems("Option one", "Option two", "Option three");
radioGroup.addThemeVariants(RadioGroupVariant.LUMO_VERTICAL);
radioGroup.setValue("Option one");

 Button button = new Button("Clear", event -> {
    radioGroup.setValue(null);
});

add(button, radioGroup);
```

![clear-group](https://user-images.githubusercontent.com/10589913/96028699-4e68b180-0e62-11eb-98d1-a1c16818c064.gif)

Closing as fixed. Please submit a new issue with a code example in case if this is still an issue.
