### ISSUE TITLE
Demo page jumpy on iOS Safari

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-radio-button#28]
Investigate: (demo issue?) on mobile (safari), after submitting the form, selecting a radio-button scrolls the page up

**Comment by Toshegg** [comment]
Bug repropduces:

- While selecting buttons in radio-group value demo
- With paper-radio-group instead of vaadin-radio-group
- When placing element outside vaadin-demo-snippet
- When there is only vaadin-button inside demo-snippet

Most probably demo issue.
