### ISSUE TITLE
Alignment issue on :focus

### ISSUE THREAD

**Issue by paales** [vaadin/vaadin-radio-button#48]
Problem doesnt occur here:
https://www.webcomponents.org/element/vaadin/vaadin-radio-button

Does occur here:
https://vaadin.com/components/vaadin-radio-button/html-examples/radio-group-demos
http://cloud.h-o.nl/qPj9

It probably has something to do with the sizing being of by one or something?

**Comment by jouni** [comment]
Yeah, it’s because of different font sizes used on the page. Lumo expects 16px, and I think on vaadin.com it ends up using 15px or some other odd number. The radio button is scaled when activated, and that causes it to “wiggle”.

**Comment by jouni** [comment]
Would be great if we can find a more robust way of rendering a uniform circle inside the radio button. Here’s how it’s currently done: https://github.com/vaadin/vaadin-radio-button/blob/master/theme/lumo/vaadin-radio-button.html#L48-L61

**Comment by jouni** [comment]
Just to add – this happens in Chrome, but not on Safari or Firefox (although the dot is slightly off-center in Firefox).

**Comment by samiheikki** [comment]
Tested this on Chrome 72 and it doesn't seem to be reproducible any more.
