### ISSUE TITLE
Default value for radio group is undefined

### ISSUE THREAD

**Issue by sudipta1411** [vaadin/vaadin-radio-button#55]
Consider the following snippet
 
      <vaadin-radio-group theme="vertical" value="{{myValue}}" >
            <vaadin-radio-button value="a1" checked>A1</vaadin-radio-button>
            <vaadin-radio-button value="a2">A2</vaadin-radio-button>
      </vaadin-radio-group>

In the above code snippet, first radio-button is initially selected. But when I print the value of `myValue`, it is `undefined`. It is set to a1/a2, only when I click on the radio-buttons. Is this expected?

**Comment by web-padawan** [comment]
Thanks for the issue and sorry about not answering earlier. This definitely looks as unexpected behaviour, although the right way would be to set `myValue` to `a1` for the initial state.

Added reproduction here: https://glitch.com/edit/#!/watery-scarf?path=index.html:15:39

The second problem here is that currently radio-group does not check for initially checked buttons, which in particular means that user can set `checked` attribute on 2 or more radio buttons by mistake. 

Note how this is different from native `<input type="radio">` which ensures only last button with `checked` attribute is actually selected (demonstrated in the same glitch).
