### ISSUE TITLE
radio-group focus sequence is incorrect when in vaadin-overlay

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-radio-button#68]
In a normal context radio-group receives focus once when looping with `tab` and `shift-tab` keys, but when it's a child of `vaadin-overlay`, it focuses each option.
The issue happens with any value of focus-trap (false or true)

![focus-group](https://user-images.githubusercontent.com/161853/42078561-44e7c472-7b7d-11e8-84a9-ac7a90701fa4.gif)

**Comment by YuriyVaadin** [comment]
Has tried to reproduce the issue in one of the demos of the `vaadin-overlay`, but has not succeed in that. @manolo, could you please confirm it is still relevant? 
![overlay-radio-group](https://user-images.githubusercontent.com/29372419/44029699-e24a2028-9f06-11e8-9203-bdc3a1643a9b.gif)

**Comment by manolo** [comment]
I can verify that it does not happen anymore.

**Comment by manolo** [comment]
Now I can see a different issue, in FF tab does not moves focus from radio-group to next focusable
code
```
    <h3>Dialog</h3>
    <vaadin-demo-snippet id="mdemo">
      <template preserve-content>
        <vaadin-button>OPEN</vaadin-button>
        <vaadin-dialog>
          <template>
            <vaadin-button>foo</vaadin-button>
            <vaadin-radio-group label="Mark">
              <vaadin-radio-button>1</vaadin-radio-button>
              <vaadin-radio-button>2</vaadin-radio-button>
              <vaadin-radio-button>3</vaadin-radio-button>
              <vaadin-radio-button>4</vaadin-radio-button>
              <vaadin-radio-button>5</vaadin-radio-button>
            </vaadin-radio-group>
            <vaadin-button>bar</vaadin-button>
          </template>
         </vaadin-dialog>


        <script>
          window.addDemoReadyListener('#mdemo', function(document) {
            var button = document.querySelector('vaadin-button');

            var dialog = document.querySelector('vaadin-dialog');

            button.addEventListener('click', function(event) {
              dialog.opened = true;
            });
          });
        </script>
      </template>
    </vaadin-demo-snippet>
```

**Comment by manolo** [comment]
Since it's a different issue let's close this and track in separated ticket https://github.com/vaadin/vaadin-radio-button/issues/77
