### ISSUE TITLE
Radio group's validity is evaluated on focus

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-radio-button#80]
When you tab to the first radio group demo on "Validation in Iron Form" page, the group, being required, is marked invalid immediately. Once you hit an arrow key to select a value, the error goes away.

![radiogrouperror](https://user-images.githubusercontent.com/1222264/44090899-6661faca-9fd4-11e8-9d74-349f25d6fe0b.gif)

**Comment by jouni** [comment]
Also, why is the label red when the field is invalid? That’s not how Lumo should work.

**Comment by web-padawan** [comment]
Label color change was added in cef0ff8
Should we use same red background for radio buttons as we have for text-field?

**Comment by web-padawan** [comment]
Confirmed this to be broken in Firefox 61 with the latest `shadydom`
After pinning `webcomponentsjs` to 1.2.0I'm unable to reproduce this issue

**Comment by jouni** [comment]
> Should we use same red background for radio buttons as we have for text-field?

That’s one option, yes. I was thinking the radio button appearance wouldn’t need to change at all, the error message is enough, but if there is no error message then it’s not clear where the error is. 

Also, the group is missing the required indicator from the label (see text-field). That should also turn red when the group is invalid, so it is in theory enough (but might be a bit too subtle to notice in practice).

Nit: the group label should follow the example guidelines and use sentence case (“Complexity level” and not “Complexity Level”).

**Comment by web-padawan** [comment]
> Also, the group is missing the required indicator from the label (see text-field). That should also turn red when the group is invalid

BTW we need to add `has-value` state attribute in order to implement it like in the text-field.

**Comment by manolo** [comment]
Separated ticket it's better for tracking

**Comment by manolo** [comment]
@tomivirkki it seems not happening anymore. Can you verify at https://cdn.vaadin.com/vaadin-radio-button/1.1.0-beta2/demo/#radio-group-validation-demos ? 

![rgroup](https://user-images.githubusercontent.com/161853/44213659-7cf97d80-a16e-11e8-9298-caa6ebcc7014.gif)

**Comment by tomivirkki** [comment]
Still happens (on FF as Sergey mentioned)

**Comment by manolo** [comment]
@web-padawan radio-group already implements `has-value` what should be done then?. 
I think documenting the attribute, and adding missing CSS rules should be ok, right ?
