### ISSUE TITLE
Not able to trigger radio buttons in code on click

### ISSUE THREAD

**Issue by andrster** [vaadin/vaadin-radio-button#84]
Hello, For the vaadin radio buttons, I can not figure out a way to programmatically trigger them(for testing). For the checkboxes I can just do .click(), but that is not working for radio. Any help with this.

**Comment by tomivirkki** [comment]
Hi, indeed `click()` seems to not work for `<vaadin-radio-button>` while it works fine with `<vaadin-checkbox>`. We'll fix this. Would `radioButton.checked = true` work for you meanwhile?

**Comment by andrster** [comment]
As a temporary solution this should be fine, eventually it would be very helpful for maintaining consistency and testing. Thank you for the quick response, it is greatly appreciated.

**Comment by limonte** [comment]
Fixed in https://github.com/vaadin/vaadin-radio-button/releases/tag/v1.1.1

Thanks for reporting @andrster!
