### ISSUE TITLE
How to listen to changes on a radio-button-group?

### ISSUE THREAD

**Issue by dflorey** [vaadin/vaadin-radio-button#96]
I'm trying to listen to changes on radio buttons in a radio-button-group in my own lit-element:
```
render() {
   return html`<vaadin-radio-group @value-changed="${console.log("Changed")} label="Risk level">
    <vaadin-radio-button value="low">Low</vaadin-radio-button>
    <vaadin-radio-button value="medium">Medium</vaadin-radio-button>
    <vaadin-radio-button value="high">High</vaadin-radio-button>
    </vaadin-radio-group>`;
}
```

The event fires just once when constructing the element, but it does not fire when clicking on the radio buttons.
How do I best listen to changes on the radio group?

**Comment by tomivirkki** [comment]
Hi, just tested at:
https://cdn.vaadin.com/vaadin-radio-button/1.1.2/demo/#radio-group-demos

by adding a listener for the "value-changed" event to the `<vaadin-radio-group>` element with:
`$0.addEventListener('value-changed', console.log)`

Seems to fire on every change

**Comment by dflorey** [comment]
You are right, seems to be an issue with custom events in lit-element (?).
Thanks a lot for looking into this!
This seems to work though:

```
render() {
   return html`<vaadin-radio-group label="Risk level">
    <vaadin-radio-button value="low">Low</vaadin-radio-button>
    <vaadin-radio-button value="medium">Medium</vaadin-radio-button>
    <vaadin-radio-button value="high">High</vaadin-radio-button>
    </vaadin-radio-group>`;
}
  
firstUpdated() {
    let shadowRoot = this.shadowRoot;
    if (shadowRoot) {
      let group = shadowRoot.querySelector('vaadin-radio-group');
      if (group) {
        group.addEventListener("value-changed", console.log);
      }
    }
}
```

**Comment by web-padawan** [comment]
Working example: https://glitch.com/edit/#!/tin-winter?path=app.js:22:0

Note that the syntax for event listener using `this._onValueChanged` is added by Polymer/lit-element#244 and supported starting from the LitElement 0.6.2

**Comment by dflorey** [comment]
Great! Thanks a lot!
